### ISSUE TITLE
Configuration: read maps from config file

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/iohk-monitoring-framework#68]
on startup we read the configuration into `Representation` as a first step.
in 'options' we can include the maps which define severity filters, subtrace creation, output selection per named context.
```
options:
  mapSeverity:
    iohk.startup: Debug
    iohk.background.process: Error
    iohk.testing.uncritical: Warning
  mapSubtrace:
    iohk.benchmarking:
      tag: ObservableTrace
      contents:
        - GhcRtsStats
        - MonotonicClock
    iohk.deadend:
      NoTrace
  mapBackends:
    iohk.interesting.value:
      - EKGViewBK
      - AggregationBK
  mapScribes:
    iohk.interesting.value:
      - "StdoutSK::stdout"
      - "FileTextSK::testlog"
    iohk.background.process:
        "FileTextSK::testlog"
```
